---
- name: apache play
  hosts: All
  become: yes
  tasks:
    - name: update ubuntu packages and intall apache
      apt:
        name: apache2
        update_Cache: yes
        state: present
          